Io turtlesim qos
rapyuta-robotics/io_tutorials pull request #5
Opened 2018-06-04 06:31 UTC by abolinsky

2018-06-04 10:00 UTC, hendrik-skubch requested changes

2018-06-04 10:00 UTC, hendrik-skubch commented on io_turtlesim/manifests/command_center.json
> +                "qos": "max"
Erm, no just low please

2018-06-04 10:00 UTC, hendrik-skubch commented on io_turtlesim/manifests/command_center.json
>              "name": "/turtle_1/goto_action"
The tutorial mentions at least actions for the first three turtles.

2018-06-04 10:00 UTC, hendrik-skubch commented on io_turtlesim/manifests/turtle.json
> +                "qos": "max"
Low, please

2018-06-04 10:21 UTC, gauthamm commented on io_turtlesim/manifests/command_center.json
> +                "qos": "max"
If we are changing it to low, we need to update the turtlesim tutorial document too.

2018-06-05 00:25 UTC, closed without merging

2018-06-05 00:26 UTC, abolinsky commented
Gautham already merged the bulk of this into master